# Site settings
title: Yonah Aviv
description: Resume
# baseurl: "" # the subpath of your site, e.g. /blog
url: "https://yonahaviv.netlify.app" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Yonah Aviv
user_description: I am a highschool student but at the same time, a relatively experienced computer programmer. I code in Python, am learning JavaScript, and learning about Machine Learning, among other things.
user_title: High school student
email: avivyonah@gmail.com
# twitter_username: lorem_ipsum
# github_username:  lorem_ipsum
# gplus_username:  lorem_ipsum

exclude: ['package.json', 'src' , 'node_modules']
